config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  devise_for :users
  resources :equipment
  resources :groups
  resources :users

  root to: "equipment#index"

  devise_scope :user do
    root to: "devise/sessions#new"
  end
end

app/models/equipment.rb
class Equipment < ApplicationRecord
    belongs_to :group 

    validates :equipment_id, :presence => true, uniqueness: { scope: :group_id, message: "Equipment id already taken"}
    validates :name, :presence => true
    validates :brand, :presence => true
    validates :model, :presence => true

    def show_description
        if self[:description] != nil
            if self[:description].gsub(/\s+/, "") == ""
                self[:description] = "No description"
            end
        end
    end

    def show_equipment_id
        if self[:equipment_id] != nil
            self[:equipment_id].to_s.rjust(6, '0')
        end
    end

    def show_group_id
        if self[:group_id] != nil
            self[:group_id].to_s.rjust(3, '0')
        end
    end

    def full_code
        self.group_id.to_s.rjust(3, '0') + '.' + self.equipment_id.to_s.rjust(6, '0')
    end
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  load_and_authorize_resource

  before_action :authenticate_user!
  before_action :get_group, only: [:show]
  before_action :set_equipment, only: [:show, :edit, :update, :destroy]

  # GET /equipment
  # GET /equipment.json
  def index
    @equipment = Equipment.all
  end

  # GET /equipment/1
  # GET /equipment/1.json
  def show
  end

  # GET /equipment/new
  def new
    @all_group = Group.all.find_all
    if @all_group.size < 1
      @group     = Group.new
      @equipment = Equipment.new
    else
      redirect_to equipment_index_url, notice: "#{translate 'equipment.none_group_created'}"
    end
  end

  # GET /equipment/1/edit
  def edit
  end

  # POST /equipment
  # POST /equipment.json
  def create
    @group     = Group.find(equipment_params[:group_id])
    @equipment = Equipment.new(equipment_params)
    
    respond_to do |format|
      if @group
        @equipment.group = @group
        if @equipment.save
          format.html { redirect_to @equipment, notice: "#{translate 'equipment.created'}" }
          format.json { render :show, status: :created, location: @equipment }
        else
          format.html { render :new }
          format.json { render json: @equipment.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :new }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipment/1
  # PATCH/PUT /equipment/1.json
  def update
    respond_to do |format|
      if @equipment.update(equipment_params)
        format.html { redirect_to @equipment, notice: "#{translate 'equipment.updated'}" }
        format.json { render :show, status: :ok, location: @equipment }
      else
        format.html { render :edit }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipment/1
  # DELETE /equipment/1.json
  def destroy
    @equipment.destroy
    respond_to do |format|
      format.html { redirect_to equipment_index_url, notice: "#{translate 'equipment.destroyed'}" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipment
      @equipment = Equipment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def equipment_params
      params.require(:equipment).permit(:id, :equipment_id, :name, :brand, :model, :description, :price, :group_id)
    end

    def get_group
      @equipment_group = Group.find(params[:id])
    end
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/views/equipment/_form.html.erb
<%= form_with(model: equipment, local: true) do |form| %>
  <% if equipment.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% equipment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br />

  <%= form.label :group, "#{translate 'equipment.group'}" %> <br />
  <%= form.collection_select :group_id, Group.all, :id, :name, {prompt: false}, {class: "form-control"} %>

  <br />

  <%= form.label :equipment_number, "#{translate 'equipment.equipment_number'}" %>
  <%= form.number_field :equipment_id, id: :equipment_equipment_id, class: "form-control", placeholder: "1" %>

  <br />

  <%= form.label :name, "#{translate 'equipment.equipment'}" %>
  <%= form.text_field :name, id: :equipment_name, class: "form-control", placeholder: "#{translate 'equipment.name_hint'}" %>

  <br />

  <%= form.label :brand, "#{translate 'equipment.brand'}" %>
  <%= form.text_field :brand, id: :equipment_brand, class: "form-control", placeholder: "#{translate 'equipment.brand_hint'}" %>

  <br />

  <%= form.label :model, "#{translate 'equipment.model'}" %>
  <%= form.text_field :model, id: :equipment_model, class: "form-control", placeholder: "#{translate 'equipment.model_hint'}" %>

  <br />

  <%= form.label :description, "#{translate 'equipment.description'}" %>
  <%= form.text_area :description, id: :equipment_description, class: "form-control", placeholder: "#{translate 'equipment.some_description'}" %>

  <br />

  <%= form.label :price, "#{translate 'equipment.price'}" %>
  <%= form.text_field :price, id: :equipment_price, class: "form-control", placeholder: "950.00" %>

  <br />

  <%= button_tag(type: 'submit', class: "btn btn-success") do %>
    <span class="glyphicon glyphicon-floppy-disk"></span>&nbsp;&nbsp;<%= translate 'actions.save' %>
  <% end %>

<% end %>

app/views/equipment/edit.html.erb
<h1><%= translate 'equipment.edit_equipment' %></h1>

<%= render 'form', equipment: @equipment %>

<br />

<%= link_to raw("<span class='glyphicon glyphicon-eye-open'></span>&nbsp;&nbsp;#{translate 'actions.show'}"), @equipment, class: "btn btn-warning" %>

<br />
<br />

<%= link_to raw("<span class='glyphicon glyphicon-arrow-left'></span>&nbsp;&nbsp;#{translate 'actions.back'}"), equipment_index_path, class: "btn btn-info" %>

app/views/equipment/index.html.erb
<h1><%= translate "equipment.title" %></h1>

<br />

<% if can? :create, Equipment %>
  <%= link_to raw("<span class='glyphicon glyphicon-plus'></span>&nbsp;&nbsp; #{translate 'equipment.new'}"), new_equipment_path, class: "btn btn-success" %>
<% end %>

<br />
<br />

<table class="table table-hover">
  <thead>
    <tr>
      <th class="text-center"><%= translate "equipment.group" %></th>
      <th class="text-center"><%= translate "equipment.code" %></th>
      <th class="text-center"><%= translate "equipment.equipment" %></th>
      <th class="text-center"><%= translate "equipment.brand" %></th>
      <th class="text-center"><%= translate "equipment.model" %></th>
      <th class="text-center"><%= translate "equipment.description" %></th>
      <th class="text-center"><%= translate "equipment.price" %></th>
      <th class="text-center" colspan="3"><%= translate "equipment.options" %></th>
    </tr>
  </thead>

  <tbody>
    <% @equipment.each do |equipment| %>
      <tr>
        <td class="text-center"><%= link_to Group.find(equipment.group_id).name, group_path(equipment.group_id) %></td>
        <td class="text-center"><%= equipment.full_code %></td>
        <td class="text-center"><%= equipment.name %></td>
        <td class="text-center"><%= equipment.brand %></td>
        <td class="text-center"><%= equipment.model %></td>
        <td class="text-center">
          <% if equipment.description.gsub(/\s+/, "") != "" %>
            <%= equipment.description %>
          <% else %>
            <%= translate 'no_description' %>
          <% end %>
        </td>
        <td class="text-center"><%= equipment.price %></td>
        <% if can? :read, Equipment %>
          <td class="text-center">
            <%= link_to raw("<span class='glyphicon glyphicon-eye-open'></span>&nbsp;&nbsp;#{translate 'actions.show'}"), equipment, class: "btn btn-info" %>
          </td>
        <% end %>
        <% if can? :edit, Equipment %>
          <td class="text-center">
            <%= link_to raw("<span class='glyphicon glyphicon-pencil'></span>&nbsp;&nbsp;#{translate 'actions.edit'}"), edit_equipment_path(equipment), class: "btn btn-warning" %>
          </td>
        <% end %>
        <% if can? :delete, Equipment %>
          <td class="text-center">
            <%= link_to raw("<span class='glyphicon glyphicon-trash'></span>&nbsp;&nbsp;#{translate 'actions.destroy'}"), equipment, method: :delete, data: { confirm: "#{translate 'confirm'}" }, class: "btn btn-danger" %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/equipment/new.html.erb
<h1><%= translate 'equipment.new' %></h1>

<%= render 'form', equipment: @equipment %>

<br />

<%= link_to raw("<span class='glyphicon glyphicon-arrow-left'></span>&nbsp;&nbsp;#{translate 'actions.back'}"), equipment_index_path, class: "btn btn-info" %>

app/views/equipment/show.html.erb
<p>
  <strong><%= translate "equipment.code" %>:</strong>
  <%= @equipment.full_code %>
</p>

<p>
  <strong><%= translate "equipment.group" %></strong>
  <%= link_to @equipment_group.name, group_path(@equipment_group) %>
</p>

<p>
  <strong><%= translate "equipment.equipment" %>:</strong>
  <%= @equipment.name %>
</p>

<p>
  <strong><%= translate "equipment.brand" %>:</strong>
  <%= @equipment.brand %>
</p>

<p>
  <strong><%= translate "equipment.model" %>:</strong>
  <%= @equipment.model %>
</p>

<p>
  <strong><%= translate "equipment.description" %>:</strong>
  <%= @equipment.show_description %>
</p>

<p>
  <strong><%= translate "equipment.price" %>:</strong>
  <%= @equipment.price %>
</p>

<br />

<% if can? :edit, Equipment %>
  <%= link_to raw("<span class='glyphicon glyphicon-pencil'></span>&nbsp;&nbsp;#{translate 'actions.edit'}"), edit_equipment_path(@equipment), class: "btn btn-warning" %>
  <br />
  <br />
<% end %>

<%= link_to raw("<span class='glyphicon glyphicon-arrow-left'></span>&nbsp;&nbsp;#{translate 'actions.back'}"), equipment_index_path, class: "btn btn-info" %>