config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  devise_for :users
  resources :equipment
  resources :groups
  resources :users

  root to: "equipment#index"

  devise_scope :user do
    root to: "devise/sessions#new"
  end
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :equipment, dependent: :destroy

    validates :id, :presence => true, :uniqueness => true
    validates :name, :presence => true, :uniqueness => true

    def show_description
        if self[:description] != nil
            if self[:description].gsub(/\s+/, "") == ""
                self[:description] = "No description"
            end
        end
    end

    def show_id
        if self[:id] != nil
            self[:id].to_s.rjust(3, '0')
        end
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource

  before_action :authenticate_user!
  before_action :get_equipments, only: [:show, :index]
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: "#{translate 'groups.created'}" }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: "#{translate 'groups.updated'}" }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: "#{translate 'groups.destroyed'}" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:id, :name, :description)
    end

    def get_equipments
      @equips_by_group = Equipment.where(group_id: params[:id])
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br />

  <%= form.label :group_cod, "#{translate 'groups.group_code'}" %>
  <%= form.number_field :id, class: "form-control", placeholder: "1" %>

  <br />

  <%= form.label :name, "#{translate 'groups.name'}" %>
  <%= form.text_field :name, id: :group_name, class: "form-control", placeholder: "#{translate 'groups.name_hint'}" %>

  <br />

  <%= form.label :description, "#{translate 'groups.description'}" %>
  <%= form.text_area :description, id: :group_description, class: "form-control", placeholder: "#{translate 'groups.some_description'}" %>

  <br />

  <%= button_tag(type: 'submit', class: "btn btn-success") do %>
    <span class="glyphicon glyphicon-floppy-disk"></span>&nbsp;&nbsp;<%= translate 'actions.save' %>
  <% end %>

<% end %>

app/views/groups/edit.html.erb
<h1><%= translate 'groups.editing_group' %></h1>

<%= render 'form', group: @group %>

<br />

<%= link_to raw("<span class='glyphicon glyphicon-eye-open'></span>&nbsp;&nbsp;#{translate 'actions.show'}"), @group, class: "btn btn-warning" %>

<br />
<br />

<%= link_to raw("<span class='glyphicon glyphicon-arrow-left'></span>&nbsp;&nbsp;#{translate 'actions.back'}"), groups_path, class: "btn btn-info" %>

app/views/groups/index.html.erb
<h1><%= translate 'groups.title' %></h1>

<br />

<% if can? :create, Group %>
  <%= link_to raw("<span class='glyphicon glyphicon-plus'></span>&nbsp;&nbsp;#{translate 'groups.new'}"), new_group_path, class: "btn btn-success" %>
<% end %>

<br />
<br />

<table class="table table-hover">
  <thead>
    <tr>
      <th class="text-center"><%= translate 'groups.group_code' %></th>
      <th class="text-center"><%= translate 'groups.name' %></th>
      <th class="text-center"><%= translate 'groups.description' %></th>
      <th class="text-center" colspan="3"><%= translate 'group.options' %></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td class="text-center"><%= group.show_id %></td>
        <td class="text-center"><%= group.name %></td>
        <td class="text-center">
          <% if group.description.gsub(/\s+/, "") != "" %>
            <%= group.description %>
          <% else %>
            <%= translate 'no_description' %>
          <% end %>
        </td>
        <% if can? :read, Group %>
          <td class="text-center">
            <%= link_to raw("<span class='glyphicon glyphicon-eye-open'></span>&nbsp;&nbsp;#{translate 'actions.show'}"), group, class: "btn btn-info" %>
          </td>
        <% end %>
        <% if can? :edit, Group %>
          <td class="text-center">
            <%= link_to raw("<span class='glyphicon glyphicon-pencil'></span>&nbsp;&nbsp;#{translate 'actions.edit'}"), edit_group_path(group), class: "btn btn-warning" %>
          </td>
        <% end %>
        <% if can? :delete, Group %>
          <td class="text-center">
            <%= link_to raw("<span class='glyphicon glyphicon-trash'></span>&nbsp;&nbsp;#{translate 'actions.destroy'}"), group, method: :delete, data: { confirm: "#{translate 'confirm'}" }, class: "btn btn-danger" %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/new.html.erb
<h1><%= translate 'groups.new' %></h1>

<%= render 'form', group: @group %>

<br />

<%= link_to raw("<span class='glyphicon glyphicon-arrow-left'></span>&nbsp;&nbsp;#{translate 'actions.back'}"), groups_path, class: "btn btn-info" %>

app/views/groups/show.html.erb
<p>
  <strong><%= translate 'groups.code' %>:</strong>
  <%= @group.show_id %>
</p>

<p>
  <strong><%= translate 'groups.name' %>:</strong>
  <%= @group.name %>
</p>

<p>
  <strong><%= translate 'groups.description' %>:</strong>
    <% if @group.description.gsub(/\s+/, "") != "" %>
      <%= @group.description %>
    <% else %>
      <%= translate 'no_description' %>
    <% end %>
</p>

<br />
<% if can? :edit, Group %>
  <%= link_to raw("<span class='glyphicon glyphicon-pencil'></span>&nbsp;&nbsp;#{translate 'actions.edit'}"), edit_group_path(@group), class: "btn btn-warning" %>
  <br />
  <br />
<% end %>

<%= link_to raw("<span class='glyphicon glyphicon-arrow-left'></span>&nbsp;&nbsp;#{translate 'actions.back'}"), groups_path, class: "btn btn-info" %>
 
<hr class="stylized">

<h3> <%= translate 'groups.equipments_group' %> </h3>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= translate 'equipment.code' %></th>
      <th><%= translate 'equipment.equipment' %></th>
      <th colspan="3"><%= translate 'equipment.options' %></th>
    </tr>
  </thead>

  <tbody>
    <% @equips_by_group.each do |equips_group| %>
      <tr>
        <td><%= equips_group.full_code %></td>
        <td><%= equips_group.name %></td>
        <% if can? :read, Equipment %>
          <td>
            <%= link_to raw("<span class='glyphicon glyphicon-eye-open'></span>&nbsp;&nbsp;#{translate 'action.show'}"), equips_group, class: "btn btn-info" %>
          </td>
        <% end %>
        <% if can? :edit, Equipment %>
          <td>
            <%= link_to raw("<span class='glyphicon glyphicon-pencil'></span>&nbsp;&nbsp;#{translate 'actions.edit'}"), edit_equipment_path(equips_group), class: "btn btn-warning" %>
          </td>
        <% end %>
        <% if can? :delete, Equipment %>
          <td>
            <%= link_to raw("<span class='glyphicon glyphicon-trash'></span>&nbsp;&nbsp;#{translate 'actions.destroy'}"), equips_group, method: :delete, data: { confirm: "#{translate 'confirm'}" }, class: "btn btn-danger" %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>