config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  devise_for :users
  resources :equipment
  resources :groups
  resources :users

  root to: "equipment#index"

  devise_scope :user do
    root to: "devise/sessions#new"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ControlePatrimonioIPC</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag     'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag  'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>


    <nav class="navbar navbar-inverse navbar-expand-sm fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to image_tag("/images/ipcandeias_black.png"), new_user_session_path %>
        </div>
        <% if current_user %>
          <ul class="nav navbar-nav navbar-left">
            <li>
              <%= link_to "#{translate 'equipment.title'}", equipment_index_url, class: "nav-link" %>
            </li>
            &nbsp;
            <li>
              <%= link_to "#{translate 'groups.title'}", groups_url, class: "nav-link" %>
            </li>
            <% if can? :read, User %>
              <li>
                <%= link_to "#{translate 'users.title'}", users_url, class: "nav-link" %>
              </li> 
            <% end %>
          </ul>
        
          <ul class="nav navbar-nav navbar-right">
            <li>
                <%= link_to raw("<span class='glyphicon glyphicon-log-out'></span> &nbsp; #{translate 'devise.login.logout'}"), destroy_user_session_path, method: :get, class: "nav-link" %>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to raw("<span class='glyphicon glyphicon-log-in'></span> &nbsp; #{translate 'devise.login.login'}"), new_user_session_path, class: "nav-link" %>
        <% end %>
          </li>
        </ul>
      </div>
    </nav>
    <div class="d-flex flex-row-reverse">
      <div class="p-2 mr-4">
        <a href="<%= request.path %>?locale=en">
          <img src="/images/united-states.png" style="width:40px;height:40px;"/>
        </a>
      </div>
      <div class="p-2">
        <a href="<%= request.path %>?locale=pt">
          <img src="/images/brazil.png" style="width:40px;height:40px;"/>
        </a>
      </div>
    </div>
  </head>

  <body>
    <div class="container pt-5">
      <% unless notice.nil? %>
        <div class="alert alert-info alert-dismissable">
          <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
          <%= notice %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>